Activities - refactoring $_SESSION - WIP
GibbonEdu/core pull request #1314
Opened 2021-04-30 05:38 UTC by hmerrettICHK

**Description**
Work in progress - first tries at refactoring $_SESSION code - please take a look and see if I'm on the right lines

**Motivation and Context**

**How Has This Been Tested?**

**Screenshots**

2021-05-03 02:31 UTC, SKuipers reviewed
Hi Harry, these are looking good, looks like you're off to a good start.

2021-05-06 08:07 UTC, SKuipers requested changes
Hi Harry, I've added some comments and areas to check out, but I haven't necessarily provided the solution. Be sure to read the code and think critically about what it means and how it's being used. Keep going, you're off to a good start!

2021-05-06 08:07 UTC, SKuipers commented on modules/Activities/report_activitySpread_formGroup.php
> +            return Format::link($session->get('absoluteURL').'/index.php?q=/modules/Students/student_view_details.php&gibbonPersonID='.$student['gibbonPersonID'].'&subpage=Activities', $name);
I suspect that this would throw an error. Check the syntax but also consider the lines above and below this line: what do you notice?

2021-05-06 08:07 UTC, SKuipers commented on modules/Activities/report_participants.php
> +        $form->addHiddenValue('q', "/modules/".$session->get($guid)['module']."/report_participants.php");
Check the syntax here. What is the variable we're looking to get?

2021-05-06 08:07 UTC, SKuipers commented on modules/Activities/report_participants.php
> +            return Format::link($session->get('absoluteURL').'/index.php?q=/modules/Students/student_view_details.php&gibbonPersonID='.$student['gibbonPersonID'].'&subpage=Activities', $name);
This looks like it would also throw an error. Read this line and the surrounding lines and consider why this might be the case.

2021-05-07 01:38 UTC, hmerrettICHK commented
Hi, Sandra! I've made the tweaks to the first couple of files (still need to commit them though), but I'm not sure what's going on with report_participants. If you have time, could you walk me through those issues a bit more?

2021-05-13 02:45 UTC, SKuipers approved these changes
Looking good, going to merge and test 👍

2021-05-13 02:45 UTC, merged