Finance - session variable refactoring (WIP)
GibbonEdu/core pull request #1329
Opened 2021-05-14 05:46 UTC by hmerrettICHK

**Description**
First set of session variable changes for Finance module

**Motivation and Context**

**How Has This Been Tested?**

**Screenshots**

2021-05-18 04:44 UTC, hmerrettICHK commented
Hi, Sandra! This PR is now complete - take a look when you can!

2021-05-27 00:55 UTC, SKuipers requested changes
Looking good overall. I've spotted one area to check out. I haven't provided the solution because I'd like you to take a look and see if you can work out why it would generate an error. Be sure you're testing these, from what I can see this would cause a fatal error.

2021-05-27 00:55 UTC, SKuipers commented on modules/Finance/expenses_manage_processBulk.php
> +    if (isActionAccessible($session, $connection2, '/modules/Finance/expenses_manage.php') == false) {
Hi Harry, please check the syntax here.

2021-05-27 07:37 UTC, SKuipers requested changes
Hi Harry, you caught one error in the syntax but the $session->set() syntax still needs some work. Keep at it!

2021-05-27 07:37 UTC, SKuipers commented on modules/Finance/expenses_manage_processBulk.php
> +                $session->set('financeExpenseExportIDs') = $gibbonFinanceExpenseIDs;
The first one looks good now, but the syntax here still needs some work

2021-05-31 01:25 UTC, SKuipers approved these changes
Looks good 👍

2021-05-31 01:25 UTC, merged