Library upgrade UI
GibbonEdu/core pull request #1794
Opened 2024-02-21 00:24 UTC by felixOlesen

**Description**

**Motivation and Context**

**How Has This Been Tested?**

**Screenshots**

2024-03-01 02:48 UTC, SKuipers commented on CHANGEDB.php
>  INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('First Aid Qualification Expiry', 'Staff', 'Manage Staff', 'Core', 'All', 'Y');end
Re-ordering the CHANGEDB, as all new entries need added at the bottom. I'll accept & commit the suggested change, no action needed on your part.

```suggestion
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('First Aid Qualification Expiry', 'Staff', 'Manage Staff', 'Core', 'All', 'Y');end
CREATE TABLE `gibbonLibraryShelf` ( `gibbonLibraryShelfID` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `name` VARCHAR(90) NOT NULL, `active` ENUM('Y','N') NOT NULL DEFAULT 'N', `field` VARCHAR(90) NOT NULL, `fieldValue` VARCHAR(90), `type` ENUM('MANUAL','AUTOMATIC') NOT NULL DEFAULT 'MANUAL', `sequenceNumber` INT(6) NOT NULL, PRIMARY KEY (`gibbonLibraryShelfID`)) ENGINE = InnoDB CHARSET=utf8;end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Library'), 'Manage Library Shelves', 0, 'Catalog', 'Allows user to manage shelves displaying library items for library browsing.', NULL, 'library_manage_shelves.php, library_manage_shelves_add.php, library_manage_shelves_edit.php, library_manage_shelves_delete.php', 'library_manage_shelves.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Library' AND gibbonAction.name='Manage Library Shelves'));end
CREATE TABLE `gibbonLibraryShelfItem` ( `gibbonLibraryShelfItemID` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `gibbonLibraryItemID` INT(10) UNSIGNED ZEROFILL NOT NULL, `gibbonLibraryShelfID` INT(6) UNSIGNED ZEROFILL NOT NULL, PRIMARY KEY (`gibbonLibraryShelfItemID`)) ENGINE = InnoDB CHARSET=utf8;end
```

2024-03-01 03:00 UTC, SKuipers requested changes
Hi Felix, this is looking amazing and well thought out, I'm really looking forward to seeing it in production. The only suggested changes I've noted are in the case consistency of your `type` field. In some places, it's used all lowercase, and other places it's used all uppercase. For consistency, both with itself and with the codebase as a whole, I've suggested changing it to Title Case in all locations. Aside from that, very keen to merge and test this out 😃

2024-03-01 03:00 UTC, SKuipers commented on CHANGEDB.php
> +CREATE TABLE `gibbonLibraryShelf` ( `gibbonLibraryShelfID` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `name` VARCHAR(90) NOT NULL, `active` ENUM('Y','N') NOT NULL DEFAULT 'N', `field` VARCHAR
```suggestion
CREATE TABLE `gibbonLibraryShelf` ( `gibbonLibraryShelfID` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `name` VARCHAR(90) NOT NULL, `active` ENUM('Y','N') NOT NULL DEFAULT 'N', `field` VARCHAR(90) NOT NULL, `fieldValue` VARCHAR(90), `type` ENUM('Manual','Automatic') NOT NULL DEFAULT 'Manual', `sequenceNumber` INT(6) NOT NULL, PRIMARY KEY (`gibbonLibraryShelfID`)) ENGINE = InnoDB CHARSET=utf8;end
```

2024-03-01 03:00 UTC, SKuipers commented on modules/Library/library_manage_shelves_add.php
> +                    'manual' => __('Manual')
```suggestion
                    'Automatic' => __('Automatic'),
                    'Manual' => __('Manual')
```

2024-03-01 03:00 UTC, SKuipers commented on modules/Library/library_manage_shelves_add.php
> +        $form->toggleVisibilityByClass('automatic')->onSelect('type')->when('automatic');
```suggestion
        $form->toggleVisibilityByClass('automatic')->onSelect('type')->when('Automatic');
```

2024-03-01 03:00 UTC, SKuipers commented on modules/Library/library_manage_shelves_addProcess.php
> +    } else if(!empty($gibbonLibraryTypeID) && $data['type'] == 'automatic') {
```suggestion
    } else if(!empty($gibbonLibraryTypeID) && $data['type'] == 'Automatic') {
```

2024-03-01 03:00 UTC, SKuipers commented on modules/Library/library_manage_shelves_edit.php
> +    if($values['type'] == 'AUTOMATIC') {
```suggestion
    if($values['type'] == 'Automatic') {
```

2024-03-01 03:00 UTC, SKuipers commented on modules/Library/library_manage_shelves_edit.php
> +    } elseif($values['type'] == 'MANUAL') {
```suggestion
    } elseif($values['type'] == 'Manual') {
```

2024-03-01 03:00 UTC, SKuipers commented on modules/Library/library_manage_shelves_add.php
> +        $form->toggleVisibilityByClass('manual')->onSelect('type')->when('manual');
```suggestion
        $form->toggleVisibilityByClass('manual')->onSelect('type')->when('Manual');
```

2024-03-01 03:00 UTC, SKuipers commented on modules/Library/library_manage_shelves_addProcess.php
> +    if(!empty($shelfItems) && $data['type'] == 'manual') {
```suggestion
    if(!empty($shelfItems) && $data['type'] == 'Manual') {
```

2024-03-01 05:24 UTC, felixOlesen commented
Hi Sandra, thanks very much for the feedback. The suggested changes look good to me so I've committed them in. 👍 I'm glad that it's all looking ok and excited to know it'll be in production soon! 😁

2024-03-01 05:41 UTC, SKuipers approved these changes
Thanks for the quick response and changes. I'm going to merge this in now and test it out 🎉

2024-03-01 05:42 UTC, merged

2024-03-04 00:54 UTC, SKuipers commented
Hi @felixOlesen Thanks again for your amazing work on this new feature, it has now gone live in ICHK, just in time for Book Week 🎉 

Post-merge, I made some tweaks and changes before pushing to production, found [in this commit](https://github.com/GibbonEdu/core/commit/c1ea66766076ee85aba808acd0c0fe290bb50f49).

- Removed the border radius, since books are square, it felt a little visually strange to see them with rounded corners.
- Lowered the transition duration, so the hover-over feels snappier.
- Changed the library search from grid to flex with flex-wrap, since the grid was causing books to overlap each other.
- Fixed a PHP notice when there are no shelves.
- Added some upper page size limits, to reduce page load time, since there is no pagination.
- Added some default library shelves for Top 20 and New Titles, so even if there are no shelves, the browse page isn't blank. These could ideally be worked into a type of automatic shelf, so they could be reordered and added/removed as desired.
- I found a tweak that can be made to the Google Books API url, to retrieve a higher quality image for some books (if ome is available), so that the book thumbnails aren't as blurry.

An additional consideration for development:

- Item status should include all copies of an item. Otherwise it may appear that the book is unavailable when it really is available in other copies.

Thanks again! It is lovely to see these changes in production just in time for book week.

![Screenshot 2024-03-04 at 08-46-12 ICHK - Gibbon - Library](https://github.com/GibbonEdu/core/assets/897700/a73ea7b0-ffe9-4588-9b36-c7244cf9186b)

2024-03-04 07:18 UTC, felixOlesen commented
Hi Sandra, these tweaks sound awesome! Thanks very much for sorting it out. I've started development on those auto-shelves, I'll make a PR draft once I have something more substantial. I'm so glad it's up and running for book week! 😁